### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by martindanko** [pendrica/azure-credentials#5]
Every time I attempt to login using azure-credentials I keep getting the follow error.

/Library/Ruby/Gems/2.0.0/gems/azure-credentials-0.1.3/lib/azure/utility/credentials.rb:153:in `password_stdin': undefined method `noecho' for #<IO:<STDIN>> (NoMethodError)

This happens and I am not able to enter my password.

**Comment by bhamilton** [comment]
I am seeing the same issue. It appears that the method 'noecho' is defined by the IO/Console library, but it is not included by the gem. Though I am still working through getting an authorization token, adding `require 'io/console'` to the top of the file (path to the gem)/azure-credentials-0.1.2/lib/azure/utility/credentials.rb gets around the error message described above.

**Comment by blackknight36** [comment]
@bhamilton Thanks for the fix.  Has anybody submitted a PR to address this issue?

**Comment by stuartpreston** [comment]
Fixed in 0.1.4
